[package]
name = "frontbin"
version = "0.1.0"
edition = "2021"

[dependencies]
galg = { path = "../galg" }
nalgebra = "0.32.4"
svg = "0.16.0"
num-traits = "0.2.18"


[dependencies.pyo3]
version = "0.20"
features = ["auto-initialize"]