[package]
name = "galg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = "1.3.2"
nalgebra = "0.32.3"
num-dual = "0.8.1"
num-traits = "0.2.18"
